spring:
  datasource:
    url: jdbc:mysql://jeeproject-proton-ac70.a.aivencloud.com:18277/defaultdb
    username: avnadmin
    password: AVNS_jseI8pdISq44gZN5skZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ressourcemanagement
